global using CatalogService.Application.Features.Queries.GetCatalogBrandsEvent;
global using CatalogService.Application.Features.Queries.GetCatalogTypesEvent;
global using CatalogService.Application.Features.Queries.GetItemsByBrandEvent;
global using CatalogService.Application.Features.Queries.GetItemsByIdEvent;
global using CatalogService.Application.Features.Queries.GetItemsByNameEvent;
global using CatalogService.Application.Features.Queries.GetItemsByTypeAndBrandEvent;
global using CatalogService.Application.Features.Queries.GetItemsEvent;